name: Depreciated build workflow

on:
  workflow_call:
    inputs:
      build_matrix_path:
        description: "Path to the build matrix file"
        default: "build.yaml"
        required: false
        type: string
      config_path:
        description: "Path to the config directory"
        default: "config"
        required: false
        type: string
      fallback_binary:
        description: "Fallback binary format, if no *.uf2 file was built"
        default: "bin"
        required: false
        type: string
      archive_name:
        description: 'Archive output file name'
        default: 'firmware'
        required: false
        type: string

jobs:
  error:
    runs-on: ubuntu-24.04
    name: Depreciation notice
    steps:
      - name: "You must update your zmk-config (click for details)"
        run: |
          echo "This action is deprecated."
          echo "Please update '.github/workflows/build.yml' in your zmk-config repository with:"
          echo "https://github.com/zmkfirmware/unified-zmk-config-template/blob/main/.github/workflows/build.yml"
          exit 1
